config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :citations do
    collection { post :import }
  end

  resources :chapters

  resources :books do
      collection { post :import }
  end

end

app/models/citation.rb
class Citation < ActiveRecord::Base
	attr_reader :author, :title, :pub_info, :classification, :line_numbers_quoted, :page_number

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |citation|
	      csv << citation.attributes.values_at(*column_names)
	    end
	  end
	end

	def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet[0]
	  puts "==================="
	  puts header
	  puts "==================="

	  (1..spreadsheet.size-1).each do |i|
	    row = Hash[[header, spreadsheet[i]].transpose]
	    citation = find_by_id(row["id"]) || new
	    citation.attributes = row.to_hash.slice(*row.to_hash.keys)
	    citation.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
		  when ".csv" then CSV.read(file.path)
		  when ".xls" then Excel.new(file.path, nil, :ignore)
		  when ".xlsx" then Excelx.new(file.path, nil, :ignore)
		  else raise "Unknown file type: #{file.original_filename}"
	  end
	end
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  before_action :set_citation, only: [:show, :edit, :update, :destroy]

  # GET /citations
  # GET /citations.json
  def index
    @citations = Citation.all
    respond_to do |format|
      format.html
      format.csv { send_data @citations.to_csv }
      format.xls # { send_data @citations.to_csv(col_sep: "\t") }
    end
  end

  def import
    Citation.import(params[:file])
    redirect_to root_url, notice: "Citations imported."
  end

  # GET /citations/1
  # GET /citations/1.json
  def show
  end

  # GET /citations/new
  def new
    @citation = Citation.new
  end

  # GET /citations/1/edit
  def edit
  end

  # POST /citations
  # POST /citations.json
  def create
    @citation = Citation.new(citation_params)

    respond_to do |format|
      if @citation.save
        format.html { redirect_to @citation, notice: 'Citation was successfully created.' }
        format.json { render :show, status: :created, location: @citation }
      else
        format.html { render :new }
        format.json { render json: @citation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /citations/1
  # PATCH/PUT /citations/1.json
  def update
    respond_to do |format|
      if @citation.update(citation_params)
        format.html { redirect_to @citation, notice: 'Citation was successfully updated.' }
        format.json { render :show, status: :ok, location: @citation }
      else
        format.html { render :edit }
        format.json { render json: @citation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /citations/1
  # DELETE /citations/1.json
  def destroy
    @citation.destroy
    respond_to do |format|
      format.html { redirect_to citations_url, notice: 'Citation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_citation
      @citation = Citation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def citation_params
      params.require(:citation).permit(:author, :title, :pub_info, :classification, :line_numbers_quoted, :page_number)
    end
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/views/citations/_form.html.erb
<%= form_for(@citation) do |f| %>
  <% if @citation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@citation.errors.count, "error") %> prohibited this citation from being saved:</h2>

      <ul>
      <% @citation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :pub_info %><br>
    <%= f.text_field :pub_info %>
  </div>
  <div class="field">
    <%= f.label :classification %><br>
    <%= f.text_field :classification %>
  </div>
  <div class="field">
    <%= f.label :line_numbers_quoted %><br>
    <%= f.text_field :line_numbers_quoted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/citations/edit.html.erb
<h1>Editing citation</h1>

<%= render 'form' %>

<%= link_to 'Show', @citation %> |
<%= link_to 'Back', citations_path %>

app/views/citations/index.html.erb
<div id="wrap">
  <div id="header"><h1>Fall of Princes Books</h1></div>
  <div id="main">
    <p>
      <h2>Import Citations</h2>

      <%= form_tag import_citations_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import" %>
      <% end %>
    </p>
    <p>
      Download:
        <%= link_to "CSV", citations_path(format: "csv") %> <!-- |
        <%= link_to "Excel", citations_path(format: "xls") %> -->
    </p>

    <table>
    <!--   <thead>
        <tr>
          <th>Author</th>
          <th>Title</th>
          <th>Pub info</th>
          <th>Page number</th>
          <th>Classification</th>
          <th>Line numbers quoted</th>
          <th>Page number</th>
          <th colspan="3"></th>
        </tr>
      </thead> -->

      <tbody>
        <% @citations.each do |citation| %>
          <tr>
            <td><%= citation[:author] %></td>
          </tr>
          <tr>
            <td><%= citation[:title] %></td>
          </tr>
          <tr>
            <td><%= citation[:pub_info] %></td>
          </tr>
          <tr>
            <td><%= citation[:page_number] %></td>
            <td><%= citation[:line_numbers_quoted] %></td>
            <td><%= citation[:classification] %></td>
          </tr>
    <!--         <td><%= link_to 'Show', citation %></td>
            <td><%= link_to 'Edit', edit_citation_path(citation) %></td>
            <td><%= link_to 'Destroy', citation, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to 'New Citation', new_citation_path %>
</div>
<br>

app/views/citations/new.html.erb
<h1>New citation</h1>

<%= render 'form' %>

<%= link_to 'Back', citations_path %>

app/views/citations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @citation.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @citation.title %>
</p>

<p>
  <strong>Pub info:</strong>
  <%= @citation.pub_info %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @citation.classification %>
</p>

<p>
  <strong>Line numbers quoted:</strong>
  <%= @citation.line_numbers_quoted %>
</p>

<%= link_to 'Edit', edit_citation_path(@citation) %> |
<%= link_to 'Back', citations_path %>