config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :citations do
    collection { post :import }
  end

  resources :chapters

  resources :books do
      collection { post :import }
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div id="wrap">
  <div id="header"><h1>Big Data Lydgate</h1></div>
  <div id="nav">
<!--     <ul>
      <li><a href="#">Option 1</a></li>
      <li><a href="#">Option 2</a></li>
    </ul>-->  
  </div>
  <div id="main">
    <p>Fall of Princes Digital Humanities Project is a software development project for analyzing the cited sections of John Lydgate's Fall of Princes.  The hypothesis is that, unlike popular works of literature such as Hamlet in which most if not all lines have been cited in other works, the citations for the Fall of Princes tend to be focused on specific sections and the majority of the work has not been cited by other works.</p>
    <br>
    <%= link_to "Books", books_path %>
<!--     <br>
    <%= link_to "Chapters", chapters_path %> -->
    <br>
    <%= link_to "Citations", citations_path %>
  </div>
  <div id="sidebar">
    <img src="images/John_Lydgate.jpg" height="250" width="200">
    <p><a href="http://commons.wikimedia.org/wiki/File:John_Lydgate.jpg#mediaviewer/File:John_Lydgate.jpg">"John Lydgate</a>" by J G Murray - Published in 1820 in The Lives of Eminent and Remarkable Characters from the Counties of Essex, Suffolk and Norfolk. Licensed under Public Domain via <a href="//commons.wikimedia.org/wiki/">Wikimedia Commons</a>.</p>
  </div>
  <div id="footer">
    <!-- <p>Footer</p> -->
  </div>
</div>